### ISSUE TITLE
Feature request (biocò): Send mail to all in depot; all in activity-area

### ISSUE THREAD

**Issue by mbschenkel** [juntagrico/juntagrico#346] opened 2021-01-12 20:51 UTC
biòco has now also migrated to the upstream Juntagrico (intranet.bioco.ch).
We are now trying to close some minor gaps to features that we had before on our custom version, and are missing now.
I could implement this myself, but would like your comments first.

We had some additional drop-downs when sending mails
![image](https://user-images.githubusercontent.com/6318378/104369657-14b94c80-551e-11eb-9f85-204c9203fd2c.png)
this allowed e.g. for the depot-admin to quickly message all "his people" or to have an activity area for everyone available on a certain weekday and message them if a job-subscriber cancelled on short notice.

In particular sending to all in depot and all in activity-area is now not possible as easily
![image](https://user-images.githubusercontent.com/6318378/104369701-28fd4980-551e-11eb-9e15-a0a93499f183.png)

The intention seems to be, that this is done by the depot resp. area admin through /my/filters/depot/nn/
But the feature is then only available to that specific person, not e.g. all admins

FYI @herrnesto

**Comment by nixnuex** [comment] 2021-01-12 20:56
The mail filter on Depot or Activity Area is also available to all admins through /my/filters as soon as #341 is fixed. Just type in the top filter box of the column of preference and then click on send mail button.

**Comment by mbschenkel** [comment] 2021-01-12 21:04
Thanks, I was just about to file that as a bug...  :-)

Does #341 refer to only the two columns Depot and Abo (pink circle below) or also the strange characters `N%~0` and `C%~0` (blue circle below)?

![image](https://user-images.githubusercontent.com/6318378/104374331-0a00b680-5522-11eb-8f36-b5d763239347.png)

**Comment by nixnuex** [comment] 2021-01-15 08:16
@motu55 what is the idea of implementation here?

As mentioned, the filters should serve as rquested for all admins in addition to the depot/TB admins. The "strange characters" in the list are on purpose for some regex filtering possibility, maybe a link to an example would help.

**Comment by mbschenkel** [comment] 2021-01-15 21:44
Actually I was mostly irritated by the code behind it in members.html, but
at a second glance it turns out to be just a fancy way to format the
numbers... 😃

If the %N is really needed by some, we could maybe show the %N greyed out
such that the numbers look less disturbing to human users?

                {% if member.assignment_count %}
                            N%-{% if member.assignment_count >= 1 and
member.assignment_count < 10 %}0{% endif %}{{
member.assignment_count|floatformat }}
                            {% else %}
                            N%-0
                            {% endif %}


nixnuex <notifications@github.com> schrieb am Fr., 15. Jan. 2021, 09:16:

**Comment by nixnuex** [comment] 2021-01-16 08:56
Example for regexp filtering in the JavaScript list filter:

`(C|N)%-0[123]?`

should filter the list based on central and normal work units between 0 and 3. This can be used to send reminder mails to people who should sign up for more jobs.

**Comment by motu55** [comment] 2021-01-16 09:35
see #351 and #352, these field will be discarded for something way cooler

**Comment by pascalfree** [comment] 2021-09-10 21:58
It seems that that the issue is solved as there are ways to achieve what was asked for.
Maybe it should be documented better?

**Comment by pascalfree** [comment] 2022-11-12 15:48
I'll close this as there is a solution in place.

**Closed by pascalfree** 2022-11-12 15:48 UTC
Labels: requires specification
