### ISSUE TITLE
Username uniqueness

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#309] opened 2020-11-08 11:54 UTC
Currently, there are two unique constraints on user level: mail address in member and username in user. The latter is generated on member creation based on first name + family name + hashed mail address and is not altered until end of lifetime. The constraints are not connected and may therefore diverge.

This can cause collisions in the following case:
1. Member signs up with mail@domain.com, a connected User is generated
2. Member changes mail address to newmail@newdomain.com, username unchanged
3. A partner member adds a new subscription with co-member based on the initial mail@domain.com address, the CS process tries to add a new member (no member with this address found) and to create a new connected User with the name and address hash which fails because its already there, connected with the "true"
Co-Member.

Either we generate a new unique username on member creation or update the username on member mail address update to avoid collisions.

**Comment by motu55** [comment] 2020-11-08 19:16
is basically a duplicate of this issue #271 respectively will be fixed by it

**Comment by nixnuex** [comment] 2020-11-08 19:46
I don't see why just moving the mail field to User would solve this issue. It's about the generation of the username, which has to be revised.

**Comment by motu55** [comment] 2020-11-08 19:51
you are right
we will have to think of something practicable

**Comment by nixnuex** [comment] 2020-11-08 19:59
The easiest: replace the mail hash in the username by a random string. We don't need the redundant information in there. This should make new usernames unique and solve the issue.

**Closed** 2021-02-04 08:40 UTC
Labels: implemented
