### ISSUE TITLE
Inactive subscriptions shown on depot filter (my/filters/depot/N)

### ISSUE THREAD

**Issue by mbschenkel** [juntagrico/juntagrico#356] opened 2021-01-19 21:51 UTC
Inactive subscriptions shown on depot filter (my/filters/depot/N).
Although such subscriptions can be filtered out (they appear with "kein Depot"), this can be misleading when a depot-admin is about to email the members in his depot, but also sends to past-members unintentionally.

![image](https://user-images.githubusercontent.com/6318378/105097124-6296fd00-5aa8-11eb-8fdd-cf239577bc5d.png)

**Side question:**
Is it intended that I need to manually assign the `juntagrico.is_depot_admin` permission to such users?
Wouldn't it be possible to have our own `@permission` that looks this up from the depot database table?

**Comment by nixnuex** [comment] 2021-01-19 22:03
First part is duplicate of #349

**Comment by mbschenkel** [comment] 2021-01-19 22:06
Uh, sorry didn't realize that.

**Comment by motu55** [comment] 2021-01-20 06:54
duplicate of #349

**Closed by motu55** 2021-01-20 06:54 UTC

**Comment by mbschenkel** [comment] 2021-01-20 07:59
@motu55 / @nixnuex: What about the side-question above? (Should maybe be discussed on Slack, but I'm not on it yet)

_Is it intended that I need to manually assign the `juntagrico.is_depot_admin` permission to such users?
Wouldn't it be possible to have our own `@permission` that looks this up from the depot database table?_

**Comment by motu55** [comment] 2021-01-20 08:04
that's the problem with packing more than one issue in an issue ;)
create a new issue

**Comment by pascalfree** [comment] 2021-01-20 12:08
> @motu55 / @nixnuex: What about the side-question above? (Should maybe be discussed on Slack, but I'm not on it yet)
> 
> _Is it intended that I need to manually assign the `juntagrico.is_depot_admin` permission to such users?
> Wouldn't it be possible to have our own `@permission` that looks this up from the depot database table?_

See #200
